<a href="https://colab.research.google.com/github/siyux1927/code-llm-finetuning/blob/dev%2Ft/notebooks/run_baseline_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# M2: Baseline Generation on Colab

在 Colab T4 GPU 上跑 `eval/generate_completions.py`，让 **未微调、4-bit 量化的 Llama-2-7B** 对 114 道 eval 题生成 completions。

产物：`data/processed/baseline_generations.jsonl`。回本地后再用 `eval/scoring.py` 算 pass@1，得到 M4 的对照基线。

> **精度设计**：baseline 用 4-bit 量化（不是 fp16），是为了跟 M3 QLoRA 训练精度一致，避免 M2→M4 的改进被"量化 vs 没量化"混淆。详见 `CLAUDE.md`。

## 前置准备清单

**开始跑之前，把下面每一项都勾掉。**

- [ ] **代码已 push 到 GitHub** — Colab 从远程 clone，本地未 push 的改动跑的不是最新版
  - `git push origin dev/t`（或你当前的分支名）
- [x] **HuggingFace 账号 + Read Token** — https://huggingface.co/settings/tokens
  - 权限选 `Read` 即可，创建后**立刻复制保存**（HF 只显示一次）
- [x] **Llama 2 授权已批准** — https://huggingface.co/meta-llama/Llama-2-7b-hf 页面点 "Request access"
  - 用**同一个 HF 邮箱**（跟 token 那个账号）
  - Meta 通常几分钟到几小时批，没批准之前 `from_pretrained` 会 403
- [ ] **Colab Runtime 选 T4 GPU** — 顶部菜单 Runtime → Change runtime type → Hardware accelerator = T4 GPU
  - 免费档就有 T4，15GB VRAM 足够跑 4-bit 7B
- [x] 【改成public】**（如果仓库是 private）GitHub Personal Access Token** — Settings → Developer settings → Personal access tokens (classic)，勾 `repo` scope

**打开这个 notebook 的方式**：Colab → File → Open notebook → GitHub tab → 粘贴仓库 URL → 选 `notebooks/run_baseline_colab.ipynb`。这样每次打开都是仓库里的最新版，不会跟本地脱节。

## 关键细节（跑之前扫一眼）

- **VRAM 预算**：T4 有 15GB，4-bit Llama-2-7B 约 4-5GB，很宽裕
- **模型首次下载**：约 13GB 权重，Colab 内网 1-2 分钟；同一 runtime 内不会重复下载
- **生成耗时**：114 题 × greedy decode（每题最多 512 tokens），预计 25-45 分钟
- **会话超时**：免费档 12 小时硬上限、90 分钟空闲断连——不要开着页面走开吃饭
- **确定性**：脚本里写死了 `do_sample=False`（greedy），相同 prompt 每次输出一样，符合 pass@1 标准做法
- **停止规则**：脚本用 `STOP_SEQUENCES`（`\ndef `、`\nclass ` 等）截断生成，防止模型跑飞把多个函数拼一起。如果观察到 completion 被截得太狠或截得不够，去 `eval/generate_completions.py` 调 `STOP_SEQUENCES`。
- **别改脚本**：这个 notebook 只是启动器，脚本原封不动跑。要改逻辑就在本地改、commit、push、然后重新在 Colab clone。

## Step 0: 确认 GPU

如果输出显示 `Tesla T4` 就 OK。如果报错 "command not found" 或没 GPU 信息 → runtime 没选对，回去改 Runtime type。

In [1]:
!nvidia-smi

Sun Jul 19 01:08:53 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Step 1: Clone 仓库

**改成你自己的 GitHub 用户名和当前分支名**，然后跑。

In [2]:
GITHUB_USER = "siyux1927"   # ← 改
BRANCH = "dev/t"                # ← 改（或者 main）
REPO = "code-llm-finetuning"

# public repo:
!git clone -b {BRANCH} https://github.com/siyux1927/code-llm-finetuning.git

# private repo（把上一行注释掉，把下面这行的 YOUR_PAT 换成你的 GitHub PAT）:
# !git clone -b {BRANCH} https://YOUR_PAT@github.com/{GITHUB_USER}/{REPO}.git

%cd {REPO}
!ls data/processed/  # 应该看到 train_50.jsonl 和 eval_114.jsonl

Cloning into 'code-llm-finetuning'...
remote: Enumerating objects: 81, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 81 (delta 22), reused 71 (delta 15), pack-reused 0 (from 0)
Receiving objects: 100% (81/81), 123.95 KiB | 991.00 KiB/s, done.
Resolving deltas: 100% (22/22), done.
/content/code-llm-finetuning
eval_114.jsonl	train_50.jsonl


## Step 2: 装依赖

`requirements-colab.txt` 是 GPU 专属依赖（`transformers`、`accelerate`、`bitsandbytes`），Mac 本地跑不了所以单独一份。

In [3]:
!pip install -q -r requirements.txt -r requirements-colab.txt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 21.0 MB/s eta 0:00:00


## Step 3: 登录 HuggingFace

运行下面 cell，弹出输入框时**粘贴你的 HF Read Token**。

如果 Step 4 报 `401` / `403` / `gated model`：
- token 无效 → 回 HF settings 重新生成
- Llama 2 授权没批 → 去 https://huggingface.co/meta-llama/Llama-2-7b-hf 检查状态

In [4]:
from huggingface_hub import login
login()

## Step 4: 跑 baseline 生成

预计 5-10 分钟。会看到每一题打印 `HumanEval/xx: generated N chars`。

如果第一题就卡很久没输出：多半是模型还在下载（13GB），耐心等 1-2 分钟第一题才会 print。

In [5]:
!python eval/generate_completions.py \
    --eval-set data/processed/eval_114.jsonl \
    --output data/processed/baseline_generations.jsonl

[gen] mode:     baseline (M2)
[gen] eval set: data/processed/eval_114.jsonl
[gen] output:   data/processed/baseline_generations.jsonl
config.json: 100% 609/609 [00:00<00:00, 2.54MB/s]
tokenizer_config.json: 100% 776/776 [00:00<00:00, 3.36MB/s]

tokenizer.model: downloading bytes:   0% 0.00/500k [00:00<?, ?B/s]
tokenizer.model: downloading bytes: 100% 346k/346k [00:00<00:00, 555kB/s, 34.4kB/s  ]
tokenizer.model: reconstructing file: 100% 500k/500k [00:00<00:00, 800kB/s, 49.6kB/s  ]
tokenizer.json: 100% 1.84M/1.84M [00:00<00:00, 46.8MB/s]
special_tokens_map.json: 100% 414/414 [00:00<00:00, 2.33MB/s]
model.safetensors.index.json: 100% 26.8k/26.8k [00:00<00:00, 59.6MB/s]
Reconstructing (incomplete total...): |          |  0.00B /  0.00B            

Fetching 2 files:   0% 0/2 [00:00<?, ?it/s]
Reconstructing (incomplete total...):   0% 0.00/9.98G [00:00<?, ?B/s]         
Reconstructing (incomplete total...):   0% 0.00/13.5G [00:00<?, ?B/s]
Reconstructing (incomplete total...):  24% 3.29G/13

## Step 5: 快速 sanity check

看一眼输出文件对不对：114 行、每行有 `task_id` 和 `completion`、`completion` 非空。

In [6]:
import json
from pathlib import Path

out = Path("data/processed/baseline_generations.jsonl")
lines = out.read_text().strip().split("\n")
print(f"总行数: {len(lines)}")

empty = 0
for line in lines:
    row = json.loads(line)
    if not row["completion"].strip():
        empty += 1
print(f"空 completion 数: {empty}")

print("\n--- 前 3 条样例 ---")
for line in lines[:3]:
    row = json.loads(line)
    print(f"[{row['task_id']}]")
    print(row['completion'][:200])
    print()

总行数: 114
空 completion 数: 0

--- 前 3 条样例 ---
[HumanEval/83]
   if n == 1:
        return 1
    elif n == 2:
        return 2
    elif n == 3:
        return 3
    elif n == 4:
        return 4
    elif n == 5:
        return 5
    elif n == 6:
        return 6

[HumanEval/69]
   if len(lst) == 0:
        return -1
    max_freq = 0
    for i in lst:
        if i > max_freq:
            max_freq = i
    if max_freq == 0:
        return -1
    return max_freq



[HumanEval/131]
   if n == 0:
        return 0
    elif n < 0:
        return 0
    elif n == 1:
        return 1
    elif n == 2:
        return 2
    elif n == 3:
        return 6
    elif n == 4:
        return 0




## Step 6: 把结果拿回本地

两种方式，二选一。

### 方式 A（推荐）：直接下载文件

文件很小（几十 KB），下完手动放回本地仓库的 `data/processed/`。

In [ ]:
from google.colab import files
files.download("data/processed/baseline_generations.jsonl")

### 方式 B：commit + push 回 GitHub

省事但要配 git 身份 + GitHub PAT。push 时提示密码就粘 PAT（不是 GitHub 登录密码）。

**注意**：如果本地那台机器同一分支也有未 push 的改动，会冲突——push 前先确认本地是干净的。

In [7]:
!git config user.email "siyux1927@proton.me"    # ← 改
!git config user.name "siyux1927"                  # ← 改

!git add data/processed/baseline_generations.jsonl
!git commit -m "M2: 添加 baseline 生成结果"
!git push origin {BRANCH}

[dev/t 68f9b5b] M2: 添加 baseline 生成结果
 1 file changed, 114 insertions(+)
 create mode 100644 data/processed/baseline_generations.jsonl
fatal: could not read Username for 'https://github.com': No such device or address


In [8]:
from getpass import getpass

# 一次性配置 git 身份（已配过就 no-op）
!git config user.email "siyux1927@proton.me"
!git config user.name "siyux1927"

# 提交（如果上一步已经 commit 了会说 "nothing to commit"，忽略即可）
!git add data/processed/baseline_generations.jsonl
!git commit -m "M2: 添加 baseline 生成结果" || echo "already committed, moving on"

# 用带 token 的 URL 一次性 push；不改 origin，token 不会写进 .git/config
pat = getpass("GitHub PAT (不会回显): ")
!git push https://{GITHUB_USER}:{pat}@github.com/{GITHUB_USER}/code-llm-finetuning.git {BRANCH}

On branch dev/t
Your branch is ahead of 'origin/dev/t' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
already committed, moving on
GitHub PAT (不会回显): ··········
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 7.54 KiB | 3.77 MiB/s, done.
Total 5 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/siyux1927/code-llm-finetuning.git
   4548623..68f9b5b  dev/t -> dev/t


## Step 7: 在 Colab 里直接算 pass@1

有了 `eval/score.py` CLI 之后不需要再回本地手工判分。这个 cell 直接给出 baseline pass@1 + 95% CI。

记这个数字——它是 M4 fine-tuned 对比的**基准线**。M4 要**至少高 9pp** 才算脱离噪声区间（见 `docs/grilling_m1_m2.md` Q1）。

In [20]:
!git log --oneline -5
!git status

aa6070e (HEAD -> dev/t) M3: 添加 LoRA adapter（r=16, α=32, 5 epochs）
68f9b5b M2: 添加 baseline 生成结果
4548623 M3+M4: 训练/评估/对比脚本全套 + docs - M3: train/train_lora.py QLoRA 微调（r=16, α=32, 5 epochs, completion-only loss）- M4: eval/generate_completions.py 加 --adapter 参数（重命名自 generate_baseline.py）- M4: eval/score.py + eval/compare_results.py CLI 工具- M2 notebook 加 pass@1 cell（Colab 内直接算，无需回本地）- 新增 notebooks/run_train_lora_colab.ipynb + run_finetuned_colab.ipynb - 新增 docs/{glossary, baseline_behavior, grilling_m1_m2, grilling_m3_pre, grilling_m4_pre}.md- requirements-colab.txt 加 peft - .gitignore 加 train/output/
81833c6 M2: 扩容评估集到 114 + max_new_tokens=512 + 忽略 .env
e0537c4 Created using Colab
On branch dev/t
Your branch and 'origin/dev/t' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	data/processed/finetuned_generations.jsonl
	lora_adapter

In [ ]:
!git pull --no-rebase --no-edit origin dev/t

In [23]:
!python eval/score.py \
    --generations data/processed/baseline_generations.jsonl \
    --eval-set    data/processed/eval_114.jsonl


pass@1 = 0.0000 (0/114)
95% CI: ±0.00pp  (SE 0.00pp, N=114)


# M3: QLoRA Fine-tuning on Colab

在 Colab T4 GPU 上跑 `train/train_lora.py`——在 4-bit 量化的 Llama-2-7B 上附加 LoRA adapter（r=16、α=32），基于 50 条 canonical HumanEval solution 训练 5 epochs。

产物：`models/lora_adapter/`（约 40-80 MB 的 LoRA 权重 + tokenizer 配置）。M4 会加载 base 模型 + 这个 adapter 做推理。

> **精度设计**：跟 M2 baseline 完全一致的 4-bit NF4 + fp16 compute——**这是让 M2→M4 差异纯粹归因于微调、而不是量化改动的关键**。详见 `docs/grilling_m3_pre.md`。

## Step 1: 跑训练

预计 15-25 分钟。会看到：

1. `[sanity]` 输出：验证 tokenization 边界（prompt 结尾 + completion 开头），确认 completion-only masking 正确
2. 训练进度条：每 step 打印 `loss` — 关注**降到多低**
3. `[m3] final adapter + tokenizer saved to models/lora_adapter`

**Loss 期望**：初始 ~2-3，健康收敛到 0.5-1.0。降到 <0.1 立刻停下——过拟合了。

In [11]:
!python train/train_lora.py

[m3] loading base model + tokenizer: meta-llama/Llama-2-7b-hf
Loading weights:   1% 2/291 [00:02<04:53,  1.02s/it]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
Loading weights: 100% 291/291 [00:45<00:00,  6.34it/s]
[m3] attaching LoRA adapter
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[m3] building dataset from data/processed/train_50.jsonl
[m3] dataset: 50 training examples
[sanity] --- first training example ---
[sanity] total tokens: 165, prompt tokens: 108
[sanity] prompt (last 80 chars): ...'cketing("(()())")\n    True\n    >>> correct_bracketing(")(()")\n    False\n    """\n'
[sanity] completion (first 80 chars): '   depth = 0\n    for b in brackets:\n        if b == "(":\n            depth += 1\n'
[sanity] --- end ---
[m3] training...
{'los

## Step 2: Sanity check adapter

确认 adapter 文件都生成了、大小正常（几十 MB）。

In [12]:
!ls -la models/lora_adapter/

# adapter_model.safetensors 应该是 30-80 MB
# adapter_config.json 是几百字节
# tokenizer 相关文件几 MB

total 159780
drwxr-xr-x 2 root root      4096 Jul 19 02:09 .
drwxr-xr-x 3 root root      4096 Jul 19 02:09 ..
-rw-r--r-- 1 root root      1103 Jul 19 02:09 adapter_config.json
-rw------- 1 root root 159967880 Jul 19 02:09 adapter_model.safetensors
-rw-r--r-- 1 root root      5202 Jul 19 02:09 README.md
-rw-r--r-- 1 root root       425 Jul 19 02:09 tokenizer_config.json
-rw-r--r-- 1 root root   3618870 Jul 19 02:09 tokenizer.json


## Step 3: 把 adapter 拿回本地

commit + push 回 GitHub

Adapter 通常 30-80MB，进 git 完全没问题（GitHub 单文件 100MB 限制）。M4 加载时直接从仓库拉。

In [14]:
import shutil
from google.colab import files

shutil.make_archive("lora_adapter", "zip", "models/lora_adapter")
files.download("lora_adapter.zip")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

## 训练完成之后

接下来 M4：加载 base 模型（同 M2 的 4-bit 量化设置）+ 这个 adapter，跑 114 题生成，用 `eval/scoring.py` 算 pass@1。跟 M2 baseline 数字对比得到微调收益。

**判断微调是否成功的门槛**（见 `docs/grilling_m1_m2.md` Q1）：M4 pass@1 需要**至少比 M2 pass@1 高 9pp** 才算脱离噪声区间。

# M4: Fine-tuned Evaluation on Colab

在 Colab T4 GPU 上跑 `eval/generate_completions.py` 加载 **base Llama-2-7B + M3 训出的 LoRA adapter**，对 114 道 eval 题生成 completions，然后：

1. 用 `eval/score.py` 算 pass@1
2. 用 `eval/compare_results.py` 跟 M2 baseline 对比——显著性 + flipped 样例

**关键设计**：生成参数（greedy / max_new_tokens=512 / STOP_SEQUENCES）跟 M2 baseline **完全一致**——差异只可能来自微调本身，不来自解码方式变了。详见 `docs/grilling_m4_pre.md`。

## Step 1: 跑 fine-tuned 生成

预计 15-25 分钟。会看到：

1. `[gen] mode: fine-tuned (M4)` — 确认加了 adapter
2. `[m4] loading LoRA adapter from ...` — 加载 adapter
3. 每题打印 `HumanEval/xx: generated N chars`

**如果报 "Adapter not found"**：M3 训练没完成或 `models/lora_adapter/` 没 push 上来——回去检查。

In [15]:
!python eval/generate_completions.py \
    --adapter models/lora_adapter \
    --eval-set data/processed/eval_114.jsonl

[gen] mode:     fine-tuned (M4)
[gen] eval set: data/processed/eval_114.jsonl
[gen] output:   data/processed/finetuned_generations.jsonl
Loading weights: 100% 291/291 [00:46<00:00,  6.23it/s]
[m4] loading LoRA adapter from models/lora_adapter
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
HumanEval/83: generated 61 chars
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface

## Step 2: Sanity check

看一眼 fine-tuned completion 长什么样——**主观判断**几条例子有没有比 baseline 更像"通用算法"（而不是硬编码 lookup）。

In [16]:
import json
from pathlib import Path

out = Path("data/processed/finetuned_generations.jsonl")
lines = out.read_text().strip().split("\n")
print(f"总行数: {len(lines)}")

empty = sum(1 for l in lines if not json.loads(l)["completion"].strip())
print(f"空 completion 数: {empty}")

print("\n--- 前 3 条样例 ---")
for line in lines[:3]:
    row = json.loads(line)
    print(f"\n[{row['task_id']}]")
    print(row['completion'][:250])

总行数: 114
空 completion 数: 0

--- 前 3 条样例 ---

[HumanEval/83]
   return sum([int(i) for i in str(n) if i.count('1') == 1])


[HumanEval/69]
   return max(i for i, cnt in enumerate(lst) if cnt >= i)


[HumanEval/131]
   prod = 1
    for i in str(n):
        if i % 2 == 1:
            prod = prod * i
    return prod if prod > 0 else 0



In [19]:
!git add notebooks/run_baseline_colab.ipynb
!git commit -m "M2+M3: 记录合并执行的 notebook（含 LoRA 训练）"
pat = getpass("GitHub PAT (不会回显): ")
!git push https://{GITHUB_USER}:{pat}@github.com/{GITHUB_USER}/code-llm-finetuning.git {BRANCH}

On branch dev/t
Your branch and 'origin/dev/t' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	data/processed/finetuned_generations.jsonl
	lora_adapter.zip

nothing added to commit but untracked files present (use "git add" to track)
GitHub PAT (不会回显): ··········
To https://github.com/siyux1927/code-llm-finetuning.git
 ! [rejected]        dev/t -> dev/t (non-fast-forward)
error: failed to push some refs to 'https://github.com/siyux1927/code-llm-finetuning.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


## Step 3: 算 pass@1

**这是 M4 的核心数字**。跟 M2 baseline 对比（下一步）。

In [25]:
!python eval/score.py \
    --generations data/processed/finetuned_generations.jsonl \
    --eval-set    data/processed/eval_114.jsonl

pass@1 = 0.0000 (0/114)
95% CI: ±0.00pp  (SE 0.00pp, N=114)


## Step 4: M4 vs M2 完整对比

这一步给出 **blog Part 2 需要的全部素材**：pass@1 delta、显著性判断、flipped 题目、5 组 side-by-side 样例。

In [24]:
!python eval/compare_results.py \
    --baseline  data/processed/baseline_generations.jsonl \
    --finetuned data/processed/finetuned_generations.jsonl \
    --eval-set  data/processed/eval_114.jsonl

Pass@1 comparison
Baseline:      0.00%   (SE ±0.00pp, N=114)
Fine-tuned:    0.00%   (SE ±0.00pp, N=114)
Delta:       +0.00pp  (95% CI ±0.00pp)
Significant at 95%? NO — within noise

Flipped problems
Base FAIL → Tuned PASS: 0 problems
Base PASS → Tuned FAIL: 0 problems (regressions)



## Step 5: Push M4 结果回仓库

把 `finetuned_generations.jsonl` commit 回去——文件小（几十 KB），进 git 完全没问题，方便 blog 复现。

In [ ]:
from getpass import getpass

# 一次性配置 git 身份（已配过就 no-op）
!git config user.email "siyux1927@proton.me"
!git config user.name "siyux1927"

# 提交（如果上一步已经 commit 了会说 "nothing to commit"，忽略即可）
!git add data/processed/baseline_generations.jsonl
!git commit -m "M2: 添加 baseline 生成结果" || echo "already committed, moving on"

# 用带 token 的 URL 一次性 push；不改 origin，token 不会写进 .git/config
pat = getpass("GitHub PAT (不会回显): ")
!git push https://{GITHUB_USER}:{pat}@github.com/{GITHUB_USER}/code-llm-finetuning.git {BRANCH}

In [30]:
!git fetch origin
!git reset --hard origin/dev/t

!git add notebooks/run_baseline_colab.ipynb
!git commit -m "M2+M3: 记录合并执行的 notebook（含 LoRA 训练）"
pat = getpass("GitHub PAT (不会回显): ")
!git push https://{GITHUB_USER}:{pat}@github.com/{GITHUB_USER}/code-llm-finetuning.git {BRANCH}

HEAD is now at 41543ea 修复 eval/score.py 和 compare_results.py 的绝对导入报错
On branch dev/t
Your branch is up to date with 'origin/dev/t'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	lora_adapter.zip

nothing added to commit but untracked files present (use "git add" to track)
GitHub PAT (不会回显): ··········
Everything up-to-date


## 完成 = MVP 完成

M4 跑完就是 Phase 1 (MVP) 全部完成。下一步：

1. **写 blog Part 2**：基于 `docs/baseline_behavior.md` + `compare_results.py` 输出 → 一篇有数字、有样例、有显著性判断的完整故事
2. **准备 M5 (quantization) / M6 (inference) / M7 (cost)**：Phase 2 生产化优化
3. **回补债务项**：如果 M4 结果反常，走 `docs/grilling_m3_pre.md` 或 `grilling_m1_m2.md` 里列的诊断项